[features]
seeds = false
skip-lint = false

[programs.devnet]
fairplay = "3YqitnvPHdQ94PWCvpTWy8CDjYiVrYCUT6D5AZUzwAK1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/eaa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'programs/fairplay/tests/fairplay_test.ts' 'programs/fairplay/tests/fairplay_edgecases_test.ts'"
